### ISSUE TITLE
Fatal error during preinstall phase

### ISSUE THREAD

**Issue by dmfenton** [asini/asini#54]
Here are my logs. I think it may be related to my project state.

```
asini(silly)   GitUtilities.isInitialized    ()
asini(silly)   GitUtilities.isInitialized    () => true
asini(silly)   GitUtilities.getTopLevelDirectory()
asini(silly)   GitUtilities.getTopLevelDirectory() => "."
asini(silly)   FileSystemUtilities.existsSync("./asini.json")
asini(silly)   FileSystemUtilities.existsSync("./asini.json") => true
asini(silly)   FileSystemUtilities.readFileSync("./asini.json")
asini(silly)   FileSystemUtilities.readFileSync("./asini.json") => "{\n  \"asini\": \"1.2.0\",\n  \"packages\": [\n    {\n      \"glob\": \"packages/*/package.json\"\n    }\n  ],\n  \"version\": \"0.0.0\"\n}"
asini(silly)   FileSystemUtilities.existsSync("./package.json")
asini(silly)   FileSystemUtilities.existsSync("./package.json") => true
asini(silly)   FileSystemUtilities.readFileSync("./package.json")
asini(silly)   FileSystemUtilities.readFileSync("./package.json") => "{\n  \"devDependencies\": {\n    \"ember-cli\": \"2.8.0\",\n    \"asini\": \"1.2.0\"\n  },\n  \"scripts\": {\n    \"bootstrap\": \"asini bootstrap\",\n    \"init\": \"scripts/init\",\n    \"publish-addons\": \"asini exec --scope ember-* npm publish\",\n    \"clean\": \"rm -rf ./packages/**/node_modules/ ./packages/**/dist ./packages/**/tmp\",\n    \"test-main\": \"asini exec --concurrency 2 --scope opendata-* -- ember -t -s\",\n    \"bower\": \"asini run bower\"\n  }\n}"
asini(verbose) Asini v1.2.0
asini(silly)   FileSystemUtilities.existsSync("./package.json")
asini(silly)   FileSystemUtilities.existsSync("./package.json") => true
asini(silly)   FileSystemUtilities.existsSync("./asini.json")
asini(silly)   FileSystemUtilities.existsSync("./asini.json") => true
asini(silly)   FileSystemUtilities.existsSync("./VERSION")
asini(silly)   FileSystemUtilities.existsSync("./VERSION") => false
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-arcgis-layout-components/package.json")
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-arcgis-layout-components/package.json") => true
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-arcgis-layout-services/package.json")
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-arcgis-layout-services/package.json") => true
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-arcgis-opendata-services/package.json")
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-arcgis-opendata-services/package.json") => true
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-cli-opendata-itempicker/package.json")
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-cli-opendata-itempicker/package.json") => true
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-cli-opendata-pages/package.json")
asini(silly)   FileSystemUtilities.existsSync("./packages/ember-cli-opendata-pages/package.json") => true
asini(silly)   FileSystemUtilities.existsSync("./packages/opendata-admin/package.json")
asini(silly)   FileSystemUtilities.existsSync("./packages/opendata-admin/package.json") => true
asini(silly)   FileSystemUtilities.existsSync("./packages/opendata-ui/package.json")
asini(silly)   FileSystemUtilities.existsSync("./packages/opendata-ui/package.json") => true
asini(verbose) Attempting running BootstrapCommand.initialize
asini(verbose) Successfully ran BootstrapCommand.initialize
asini(verbose) Attempting running BootstrapCommand.execute
asini(info)    Bootstrapping 7 packages
asini(info)    Preinstalling packages
asini(error)   Errored while running BootstrapCommand.execute
    TypeError: Cannot read property 'slice' of undefined
        at ProgressBarController.tick (opendata/node_modules/asini/lib/progressBar.js:61:47)
        at opendata/node_modules/asini/lib/commands/BootstrapCommand.js:132:34
        at Package.runScript (opendata/node_modules/asini/lib/Package.js:65:9)
        at  opendata/node_modules/asini/lib/commands/BootstrapCommand.js:131:17
        at opendata/node_modules/async/lib/async.js:718:13
        at replenish (opendata/node_modules/async/lib/async.js:319:21)
        at opendata/node_modules/async/lib/async.js:330:15
        at _parallel (opendata/node_modules/async/lib/async.js:717:9)
        at Object.async.parallelLimit (opendata/node_modules/async/lib/async.js:735:9)
        at bootstrapBatch (opendata/node_modules/asini/lib/commands/BootstrapCommand.js:129:25)

```

**Comment by gigabo** [comment]
Oh, interesting... Do you have any packages with `preinstall` scripts?

I'll bet we're just not accounting for the case of repos without any. :thinking:

**Comment by dmfenton** [comment]
I don't think so. For more info these are a bunch of Ember packages.

**Comment by gigabo** [comment]
Okay, so the only way I was able to reproduce this locally was actually to try to bootstrap with no packages at all. 😬 

So I filed #55 to provide better behavior in that case.

But that makes me wonder if your asini repo might have something mis-configured so it's not finding your packages.

Do you get expected output from `asini ls`?

**Comment by dmfenton** [comment]
I do get the expected output. The problem seems to have come and gone. I'm not sure what it was about my state.

Is there a way to disable the progress bar altogether?

**Comment by gigabo** [comment]
Huh, weird. 😕 

> Is there a way to disable the progress bar altogether?

There actually isn't.  An option to disable it might be a nice enhancement.
