### ISSUE TITLE
Bug with nested deps

### ISSUE THREAD

**Issue by dmfenton** [asini/asini#57]
I'm running into this when running tests on CI. Lerna does not show this behavior so I think it's probably an issue with hoisting.

```
> asini exec --concurrency 2 --scope opendata-* -- ember t ci --silent
Cannot find module 'lodash/object/merge'
Error: Cannot find module 'lodash/object/merge'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/ArcGIS/opendata-ui/packages/opendata-admin/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/lib/style-plugin.js:5:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by gigabo** [comment]
Hmm... Does it repro after an `asini bootstrap --nohoist`?  If not that would help confirm that it's related to hoisting (as opposed to some other difference between Asini and Lerna).
