### ISSUE TITLE
`asini diff` reports error on quitting by key `q`

### ISSUE THREAD

**Issue by mocheng** [asini/asini#82]
If there is no diff since last release, or if I press key `q` to quit reviewing diff, `asini diff` command dumps a error message as below.
>Errored while running DiffCommand.execute
Error: Errored while spawning `git diff`.
    at /usr/local/lib/node_modules/asini/lib/commands/DiffCommand.js:77:20
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/asini/lib/ChildProcessUtilities.js:100:11)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

In source code https://github.com/asini/asini/blob/master/src/commands/DiffCommand.js#L39 , it reports error if `git diff` command response code is not `0`. However, if there is no diff and or diff process is aborted, the response code is `null`. These situation should be taken into consideration.

**Comment by gigabo** [comment]
Hi @mocheng sorry you ran into trouble.  If you were seeing this on React Server a pull from master should fix it up for you.  React Server has [migrated back to Lerna](https://github.com/redfin/react-server/pull/877).  Asini is no longer maintained.

**Comment by mocheng** [comment]
@gigabo Actually I ran into this trouble for my own project based on react-server. Since react-server is moving back to Lerna. Perhaps I need to choose a right time to do same thing.
